name: CI

on: 
  push:
    branches:
    - master

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
       node-version: '16.14.2'
    - run: npm install
    - run: npm run build
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
          repoToken: ${{ secrets.FIREBASE_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_POORTI_21857 }}
          projectId: poorti-21857
      env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_POORTI_21857 }}
